-- ============================================================
-- Urban Furniture — Seed data
-- Run AFTER schema.sql
-- Dev only: fixed ADMIN password below must be changed for
-- any real deployment (see README section 5).
-- ============================================================

BEGIN;

-- ---------- Fixed ADMIN user ----------
-- Password: Admin@12345
-- Hash generated with bcryptjs (10 rounds). Regenerate with
-- `node src/utils/hashPassword.js Admin@12345` if it ever needs to change.
INSERT INTO users (name, login_id, email, password_hash, role, is_active)
VALUES (
  'System Admin',
  'admin',
  'admin@urbanfurniture.local',
  '$2b$10$V.XZvhjLkwSpauLcLlMkXOBuL99DmHdJbMDkHOGTkbEKq.vilXS7i', -- bcrypt hash of Admin@12345 (10 rounds)
  'ADMIN',
  TRUE
)
ON CONFLICT (login_id) DO NOTHING;

-- ---------- Base Chart of Accounts ----------
INSERT INTO chart_of_accounts (name, account_type, account_subtype) VALUES
  ('Cash', 'ASSET', 'Current Asset'),
  ('Bank', 'ASSET', 'Current Asset'),
  ('Debtors', 'ASSET', 'Receivable'),
  ('Inventory', 'ASSET', 'Current Asset'),
  ('Creditors', 'LIABILITY', 'Payable'),
  ('Tax Payable', 'LIABILITY', 'Current Liability'),
  ('Capital', 'CAPITAL', 'Owner Equity'),
  ('Sales Income', 'INCOME', 'Operating Income'),
  ('Purchases Expense', 'EXPENSE', 'Cost of Goods Sold'),
  ('Operating Expense', 'EXPENSE', 'Operating Expense')
ON CONFLICT (name) DO NOTHING;

-- ---------- Base Journals ----------
INSERT INTO journals (name, journal_type, default_account_id)
SELECT 'Sales Journal', 'SALES', id FROM chart_of_accounts WHERE name = 'Sales Income'
ON CONFLICT (name) DO NOTHING;

INSERT INTO journals (name, journal_type, default_account_id)
SELECT 'Purchase Journal', 'PURCHASE', id FROM chart_of_accounts WHERE name = 'Purchases Expense'
ON CONFLICT (name) DO NOTHING;

INSERT INTO journals (name, journal_type, default_account_id)
SELECT 'Bank Journal', 'BANK', id FROM chart_of_accounts WHERE name = 'Bank'
ON CONFLICT (name) DO NOTHING;

INSERT INTO journals (name, journal_type, default_account_id)
SELECT 'Cash Journal', 'CASH', id FROM chart_of_accounts WHERE name = 'Cash'
ON CONFLICT (name) DO NOTHING;

INSERT INTO journals (name, journal_type)
VALUES ('General Journal', 'GENERAL')
ON CONFLICT (name) DO NOTHING;

-- ---------- Base Product Category ----------
INSERT INTO product_categories (name) VALUES ('Uncategorized')
ON CONFLICT (name) DO NOTHING;

COMMIT;

-- NOTE: this seed intentionally stops at reference/master data.
-- The 200+ realistic records required by the acceptance checklist
-- (section 44) should be generated by a separate scripts/seedDemoData.js
-- once the business tables and controllers exist, so quantities and
-- totals stay consistent with the actual calculation logic.
